### ISSUE TITLE
Add preflight check

### ISSUE THREAD

**Issue by luyseyal** [StEdwardsTeam/PrintToBox#13]
The Box API allows for a preflight check to ensure a file will not use up all available space before a transfer is complete. This saves network hassle for everyone.

The downside is yet another API roundtrip which increases execution time.

**Comment by mishatx** [comment]
As an option or mandatory?  Box for education accounts are for all intents and purposes unlimited space so we might choose to skip the extra API call.

**Comment by luyseyal** [comment]
I ran into the issue uploading. My account is flagged as a 10GB account and I've uploaded some massive junk recently and it timed out. I've since requested in a support ticket that I be allocated the proper 50GB.

**Comment by luyseyal** [comment]
I think it's also probably important since the service account itself might run out of space if for some reason it ran into trouble giving away access to lots and lots of little folders -- e.g., if AutoAccept shares is turned off in the Enterprise Settings. Just a supposition at this point.

For reference later: 
`BoxFolder.canUpload(String name, long fileSize)`
`BoxFile.canUploadVersion(String name, long fileSize, String parentID)`
