### ISSUE TITLE
Support subdirectory creation/population

### ISSUE THREAD

**Issue by luyseyal** [StEdwardsTeam/PrintToBox#3]
Support subdirectory creation/population

**Comment by luyseyal** [comment]
@mishatx 

Can you evaluate if you really need scenario [1] or if judicious use of [2] is sufficient?

1. `<Collab Folder>/<Normal Folder>`
2. `<Normal Folder>/<Collab Folder>`

What's top-level for PrintToBox may not be what's top-level for the user. 

The user can already remap the collab folder into a normal folder in their own space transparently. So they can already have:

```
/BannerJobs/FinAidProcXYZ/...
/BannerJobs/ICGORLDI/...
/BannerJobs/PrintToBox login/...
```

Where "FinAidProcXYZ", "ICGORLDI", and "PrintToBox login" are top-level collaborations in the PrintToBox space.

Having said that, it is important to be judicious with the PrintToBox namespace because it is flat. One-per-enterprise.

So, you wouldn't want to have `PrintToBox -f "jobs" ...` or `PrintToBox -f "Financial Aid"...` because there are likely to be collisions.

**Comment by mishatx** [comment]
(2) is fine, although I can't see an easy way to set that up in the box interface.   

I can create a new folder, but I can't put existing collab folders in it.

**Comment by luyseyal** [comment]
Create the directory but don't go into it. Click the down arrow menu for "PrintToBox mikem" and select copy/move. Move it into the directory you just created.

**Comment by mishatx** [comment]
Ah, so I can do that on folders where I am the owner, but not folders where I am the editor.

**Comment by luyseyal** [comment]
Yeah, I guess so. Hadn't noticed that before. Since PrintToBox is going to be uploading to a folder owner's folder (or complain/abort), that should be OK.

Kind of annoying that if Financial Aid wanted to share it around, folks couldn't move the collaborated folder into their own hierarchy. I know my folders are getting out of hand.

**Comment by luyseyal** [comment]
Oh well, I guess that's what search is for... though I am not a big fan of the Gmail approach.

**Comment by mishatx** [comment]
Yes it aches for organization.  

I think in most cases, this isn't a problem where people will be print-to-boxing for folders they own, but in situations where we have finance or financial aid processes that run regularly and then send the files to box, this is more problematic.

For finance, we just set up new collab folders called "Finance_cron_FUPLOAD" "Finance_cron_FURFEED" etc.  This is fine, but it adds to the folder soup for people who are shared to the folders.

**Comment by luyseyal** [comment]
So would a "Finance_Cron" collab folder with subfolders for "FUPLOAD" and "FURFEED" be better?

Playing around with it more in the web interface, it looks like the top-level perms are inherited when a subfolder is created. So long as the owner of the top level shared folder hasn't mucked with it, it seems this could be feasible. I just don't want to worry about permissions on the subfolders. 

Looks like an owner can't give away ownership of a subfolder so we should be good.

**Comment by mishatx** [comment]
Better in the sense that it would be less messy and would mirror what they had on edshare.

Functionality-wise, I'm not so sure. Cui I think has found a good use for being able to set the perms for each type of file separately.

**Comment by luyseyal** [comment]
Yeah, it looks like users can be *added* for subfolders but if they're inherited from the parent, you're stuck with whatever you give them. So in the Finance_Cron case, the owner of Finance_Cron would have to give individuals access at the lower levels (Finance_Cron/FURFEED).
