### ISSUE TITLE
-f will only upload one folder deep

### ISSUE THREAD

**Issue by brandnewmath** [StEdwardsTeam/PrintToBox#31]
It appears PrintToBox's -f option cannot write to any folder more than one layer deep. Example:

$ PrintToBox -f "FolderName" username filename.txt

...works just fine, but try to specify a that it should upload to a subfolder and you get an error:

$ PrintToBox -f "FolderName/SubFolderName" username filename.txt

This creates a folder called "FolderName" (even if one with that name already existed), and displays an error like the following:

Error: Could not properly set collaboration on the folder:
1) Check that user 'username' exists in Box.
2) Check that enterpriseDomain '@example.com' is correct
3) Ensure the user does not have a folder 'FolderName' already
com.box.sdk.BoxAPIException: The API returned an error code: 409
{
    "type": "error",
    "status": 409,
    "code": "item_name_in_use",
    "context_info": {
        "conflicts": null
    },
    "help_url": "http://developers.box.com/docs/#errors",
    "message": "Item with the same name already exists",
    "request_id": "123456789012ab345c678d"
}

It's possible I'm using the wrong path separator or doing something else wrong. Thanks!

**Comment by brandnewmath** [comment]
I should clarify that the above only happens when the first folder ("FolderName" in my examples) already exists. If it doesn't, PrintToBox creates the whole path as expected.

**Comment by luyseyal** [comment]
Make sure it's shared with the robot account. EDITOR permission.

-sw

**Comment by brandnewmath** [comment]
That solves the issue described above--thanks! However, there is a closely related issue: if someone shares a subfolder with the PrintToBox user, but PrintToBox does not have permissions on the folders above that subfolder, the same error occurs, including the creation of the duplicate folder.

**Comment by luyseyal** [comment]
Yep. It only understands top-level collaborations. I don't recall the exact
reason why it didn't work but it definitely doesn't.

-sw

**Comment by brandnewmath** [comment]
Thanks, I'll confer with my counterparts on this matter.
