### ISSUE TITLE
PrintToBox command exits with status 0 even on failure

### ISSUE THREAD

**Issue by brandnewmath** [StEdwardsTeam/PrintToBox#32]
At least in some cases, even when PrintToBox throws an exception and fails to upload a file, it exits with a status of 0, which indicates success. This makes it difficult to determine if an upload succeeded or failed when running it in a script. The specific case in which I observed this behavior is related to issue #31 .

**Comment by luyseyal** [comment]
This is a good bug. Thank you! I may do an interim 1.5 release for this since [Box Java SDK 1.2.0](https://github.com/box/box-java-sdk) isn't out yet for the PrintToBox 2.0 release I'm planning.
